/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripletexRouteImport } from './routes/tripletex'
import { Route as IndexRouteImport } from './routes/index'

const TripletexRoute = TripletexRouteImport.update({
  id: '/tripletex',
  path: '/tripletex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tripletex': typeof TripletexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tripletex': typeof TripletexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tripletex': typeof TripletexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tripletex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tripletex'
  id: '__root__' | '/' | '/tripletex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripletexRoute: typeof TripletexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tripletex': {
      id: '/tripletex'
      path: '/tripletex'
      fullPath: '/tripletex'
      preLoaderRoute: typeof TripletexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripletexRoute: TripletexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
